(******************************************************************************)
(*                                                                            *)
(*                 Mazur's Torsion Theorem: Elliptic Curve Classification     *)
(*                                                                            *)
(*     Formalizes Mazur's 1977 classification of torsion subgroups of         *)
(*     elliptic curves over ℚ: E(ℚ)_tors ∈ {ℤ/nℤ : n ≤ 10 or n = 12} ∪       *)
(*     {ℤ/2ℤ × ℤ/2nℤ : n ≤ 4}. Proves exactly 15 isomorphism classes via     *)
(*     modular curve analysis and Eisenstein quotient bounds.                 *)
(*                                                                            *)
(*     "The problem of torsion is the problem of modular curves."             *)
(*     - Barry Mazur, 1977                                                    *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 7, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
